
version: "3.8"
services:
  snaketestapp:
    image: jacjamg/testauto:latest
    build: .
    container_name: testauto
    ports:
      - "80:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
    command: ["node", "app.js"]
   


